feat : add avatar and badge components
viru2001/Cool-UI pull request #5
Opened 2022-02-04 16:45 UTC by viru2001

2022-02-04 17:48 UTC, akshay-rajput requested changes
make these minor changes

2022-02-04 17:48 UTC, akshay-rajput commented on components/Avatar/avatar.css
> +.avatar-lg-text{
no need for these classes

2022-02-04 17:48 UTC, akshay-rajput commented on components/Avatar/avatar.css
> +.avatar-lg{
include height here

2022-02-04 17:48 UTC, akshay-rajput commented on components/Badge/badge.css
> +  bottom: 1.2rem;
this class is using positioning properties.. use proper name here..

2022-02-04 17:48 UTC, akshay-rajput commented on components/Badge/badge.css
> +.status-offline {
should be badge-status-offline

2022-02-04 17:48 UTC, akshay-rajput commented on components/Badge/badge.css
> +.text-badge{
name and property type mismatch

2022-02-05 01:47 UTC, Mohasin-Haque reviewed
Your code is clean and its good to merge but need to work on the commented part as well..

2022-02-05 01:47 UTC, Mohasin-Haque commented on components/Avatar/avatar.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
Can add meta descriptions to personalise it more.
Like <meta name="author" content="Viresh" />
    <meta name="description" content="about your ui" />

2022-02-05 01:47 UTC, Mohasin-Haque commented on components/Badge/badge.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
same can be done here also

2022-02-09 11:08 UTC, merged